project_id = "protection-giants-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
auto_expose_new_tables = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[analytics]
enabled = false
