-- Center Network Approval Foundation (Cube B)
-- Migration name generated by Supabase CLI 2.105.0.

alter table public.installation_centers
  add column approval_status text not null default 'unapproved',
  add column approved_at timestamptz,
  add column approved_by_profile_id uuid
    references public.profiles(id) on delete restrict;

alter table public.installation_centers
  add constraint installation_centers_approval_status_allowed
    check (approval_status in ('unapproved', 'approved')),
  add constraint installation_centers_approval_projection_consistent
    check (
      (approval_status = 'unapproved' and approved_at is null and approved_by_profile_id is null)
      or
      (approval_status = 'approved' and approved_at is not null and approved_by_profile_id is not null)
    );

create or replace function public.reject_center_approval_on_entity_insert()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.approval_status <> 'unapproved'
    or new.approved_at is not null
    or new.approved_by_profile_id is not null
  then
    raise exception using
      errcode = '23514',
      message = 'Center network approval must be granted after Center creation';
  end if;

  return new;
end;
$$;

revoke all on function public.reject_center_approval_on_entity_insert() from public;
revoke all on function public.reject_center_approval_on_entity_insert() from anon;
revoke all on function public.reject_center_approval_on_entity_insert() from authenticated;
revoke all on function public.reject_center_approval_on_entity_insert() from service_role;

create trigger installation_centers_initial_approval_unapproved
before insert on public.installation_centers
for each row execute function public.reject_center_approval_on_entity_insert();

create table public.center_network_approval_events (
  id uuid primary key default gen_random_uuid(),
  installation_center_id uuid not null
    references public.installation_centers(id) on delete restrict,
  action text not null,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),

  constraint center_network_approval_events_action_allowed
    check (action in ('approved', 'revoked', 'location_changed'))
);

create index center_network_approval_events_center_occurred_idx
  on public.center_network_approval_events (installation_center_id, occurred_at desc, id desc);

alter table public.center_network_approval_events enable row level security;

revoke all on table public.center_network_approval_events from public;
revoke all on table public.center_network_approval_events from anon;
revoke all on table public.center_network_approval_events from authenticated;
revoke all on table public.center_network_approval_events from service_role;

grant select on table public.center_network_approval_events to authenticated;

create policy "center_network_approval_events_admin_agent_read"
on public.center_network_approval_events
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.status = 'active'
      and (
        (
          p.role = 'admin'
          and p.country_agent_id is null
          and p.dealer_id is null
          and p.installation_center_id is null
        )
        or (
          p.role = 'agent'
          and p.country_agent_id is not null
          and p.dealer_id is null
          and p.installation_center_id is null
          and exists (
            select 1
            from public.country_agents ca
            where ca.id = p.country_agent_id
              and ca.status = 'active'
          )
          and exists (
            select 1
            from public.installation_centers c
            left join public.dealers d on d.id = c.dealer_id
            where c.id = center_network_approval_events.installation_center_id
              and (
                c.country_agent_id = p.country_agent_id
                or d.country_agent_id = p.country_agent_id
              )
          )
        )
      )
  )
);

create or replace function public.reject_center_network_approval_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception using
    errcode = '55000',
    message = 'center network approval events are immutable';
end;
$$;

revoke all on function public.reject_center_network_approval_event_mutation() from public;
revoke all on function public.reject_center_network_approval_event_mutation() from anon;
revoke all on function public.reject_center_network_approval_event_mutation() from authenticated;
revoke all on function public.reject_center_network_approval_event_mutation() from service_role;

create trigger center_network_approval_events_immutable
before update or delete on public.center_network_approval_events
for each row execute function public.reject_center_network_approval_event_mutation();
