-- Cube M migration scaffold retained as an intentional no-op.
--
-- This file was created by `supabase migration new` before the existing Cube M
-- implementation timestamps (20260825010000..20260825013500). Executing the
-- read layer here would therefore precede the Warranty schema foundation.
--
-- The actual Increment 3 read layer is implemented in:
--   20260825020000_cube_m_internal_warranty_read_layer.sql
--
-- Cube M is still unmerged and has not been applied to Production. Retaining
-- this scaffold as a no-op preserves migration history while making the
-- dependency order explicit and deterministic.
