-- Cube E increment 1: official Product GTIN.
-- GTIN is a Product-level trade-item identifier and remains distinct from
-- SKU, Roll serial, ERP serial, Transfer ID and future Activation/Warranty IDs.

alter table public.products
  add column gtin text;

create function private.is_valid_gtin(p_value text)
returns boolean
language plpgsql
immutable
strict
set search_path = ''
as $$
declare
  v_length integer;
  v_sum integer := 0;
  v_weight integer := 3;
  v_index integer;
  v_check_digit integer;
begin
  v_length := char_length(p_value);

  if v_length not in (8, 12, 13, 14)
     or p_value !~ '^[0-9]+$' then
    return false;
  end if;

  v_check_digit := right(p_value, 1)::integer;

  for v_index in reverse (v_length - 1)..1 loop
    v_sum := v_sum + (substr(p_value, v_index, 1)::integer * v_weight);
    v_weight := case when v_weight = 3 then 1 else 3 end;
  end loop;

  return ((10 - (v_sum % 10)) % 10) = v_check_digit;
end;
$$;

revoke all on function private.is_valid_gtin(text)
  from public, anon, authenticated, service_role;

alter table public.products
  add constraint products_gtin_valid
    check (
      gtin is null
      or (
        gtin = btrim(gtin)
        and private.is_valid_gtin(gtin)
      )
    );

create unique index products_gtin_unique
  on public.products (gtin)
  where gtin is not null;

create function private.prevent_produced_product_gtin_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.gtin is not null
     and new.gtin is distinct from old.gtin
     and exists (
       select 1
       from public.production_orders as production_order
       where production_order.product_id = old.id
         and production_order.status = 'generated'
     )
  then
    raise exception 'Produced Product GTIN is locked after assignment. Create a new Product/SKU for a different trade item.'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

revoke all on function private.prevent_produced_product_gtin_change()
  from public, anon, authenticated, service_role;

create trigger products_lock_produced_gtin
before update of gtin
on public.products
for each row
execute function private.prevent_produced_product_gtin_change();

comment on column public.products.gtin is
  'Optional official GS1 GTIN (8/12/13/14 digits). Stored as text to preserve leading zeroes; never generated by the platform.';
comment on function private.prevent_produced_product_gtin_change() is
  'Allows one-time NULL-to-GTIN assignment after production, then preserves the Product trade-item identity while generated production exists.';
