-- Public Center Directory & Map (Cube C)
-- Migration name generated by Supabase CLI 2.105.0.

create view public.public_center_directory
with (security_barrier = true)
as
select
  c.name as center_name,
  c.city,
  c.country_code,
  c.latitude,
  c.longitude,
  case
    when c.approval_status = 'approved' then 'approved'::text
    else 'registered'::text
  end as classification
from public.installation_centers c
where c.status = 'active'
  and c.latitude is not null
  and c.longitude is not null
  and c.location_captured_at is not null
  and c.location_source is not null
  and c.location_updated_by_profile_id is not null;

comment on view public.public_center_directory is
  'Narrow public projection for active located Centers only.';

revoke all on table public.public_center_directory from public;
revoke all on table public.public_center_directory from anon;
revoke all on table public.public_center_directory from authenticated;
revoke all on table public.public_center_directory from service_role;

grant select on table public.public_center_directory to anon;
grant select on table public.public_center_directory to authenticated;
